import ReviewCartItem from "../component/customer/review-cart-item";
import PricingCard from "../component/customer/pricing-card";
import Head from 'next/head';
import styles from '../styles/Home.module.css';

// Component
import Navbar from "../component/customer/Navbar";
import Footer from "../component/customer/Footer";
// Utils
import {withAuth} from "../utils/gsspCustomer";

export const getServerSideProps = withAuth(context => {
    // Your normal `getServerSideProps` code here
    return { props: {} };
});

export default function Home({isLogin, currentUser}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isLogin={isLogin} currentUser={currentUser} />
      
      <div className="container py-4">
        <div className="row g-3">
          <div className="col-lg-8">
            <div className="card border-0 shadow-sm">
              <div className="card-body">
                <h4 className="fw-semibold mb-3">Barang di Keranjang</h4>
                <div className="row row-cols-1 row-cols-md-2 g-3">
                  <div className="col">
                    <ReviewCartItem />
                  </div>
                  <div className="col">
                    <ReviewCartItem />
                  </div>
                  <div className="col">
                    <ReviewCartItem />
                  </div>
                </div>
                <hr className="text-muted" />
                <div className="row g-3">
                  <div className="col-md-6">
                    <h4 className="fw-semibold">Alamat Pemesan</h4>
                    <div className="vstack text-dark small">
                      <span>Milk Mocha</span>
                      <span>No. 33, Mocha Street, Milk Township</span>
                      <span>Yangon, Myanmar</span>
                      <span>Tel: +95911223344</span>
                      <span>Email: milkmocha@domain.com</span>
                    </div>
                  </div>
                  <div className="col-md-6">
                    <h4 className="fw-semibold">Pembayaran</h4>
                      <select class="form-select" aria-label="Default select example">
                        <option selected>Pilih Opsi Pembayaran</option>
                        <option value="1">Tunai</option>
                        <option value="2">Gopay</option>
                        <option value="3">Gusto</option>
                      </select>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-lg-4">
            <PricingCard pricingOnly>
              <div className="d-grid gap-2 mt-2">
                <button
                  className="btn btn-success"
                  onClick={() => {
                    router.push({
                      pathname: "/checkout/checkout-success",
                    });
                  }}
                >
                  Konfirmasi
                </button>
                {/* <Link href="/checkout/payment-info">
                  <a className="btn btn-outline-primary">Return</a>
                </Link> */}
              </div>
            </PricingCard>
          </div>
        </div>
      </div>
      <Footer/>
    </div>
  )
}