import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// Component
import Navbar from "../component/customer/Navbar";
import Footer from "../component/customer/Footer";
// Utils
import {withAuth} from "../utils/gsspCustomer";

export const getServerSideProps = withAuth(context => {
    // Your normal `getServerSideProps` code here
    return { props: {} };
});

export default function Home({isLogin, currentUser}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Detail Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isLogin={isLogin} currentUser={currentUser} />
      
      <div>
        <div className="row m-4 gy-3 gx-4">
              <div className="col-lg-5">
                <div className="row">
                  <div className="col-12">
                    <div className="ratio ratio-1x1">
                      <img
                        className="rounded"
                        src={`https://source.unsplash.com/random/300x300?random=${Math.floor(
                          Math.random() * 50
                        )}`}
                        width={300}
                        height={300}
                        alt="Product image."
                      />
                    </div>
                  </div>
                </div>
                <div className="row mt-3 d-none d-lg-block">
                  <div className="col-12 d-flex justify-content-center">
                  </div>
                </div>
              </div>

              <div className="col-lg-7">
                <div className="d-flex">
                  <div className="d-inline h2 mb-0 fw-semibold me-3">
                    Product name here
                  </div>
                </div>

                <div className="vstack">
                  <div className="d-flex mb-3 gap-2">
                    <span className="text-muted small">150 orders</span>
                    <span className="text-success small">
                      &nbsp;In Stock
                    </span>
                  </div>
                  <h4 className="fw-semibold">15000Ks</h4>
                  <p className="fw-light">
                    Lorem ipsum is placeholder text commonly used in the graphic,
                    print, and publishing industries for previewing layouts and
                    visual mockups.
                  </p>
                  <dl className="row mb-0">
                    <dt className="col-sm-3 fw-semibold">Code#</dt>
                    <dd className="col-sm-9">10001</dd>
                    <dt className="col-sm-3 fw-semibold">Category</dt>
                    <dd className="col-sm-9">Electronics</dd>
                    <dt className="col-sm-3 fw-semibold">Delivery</dt>
                    <dd className="col-sm-9">Yangon, Mandalay</dd>
                  </dl>
                  <hr className="text-muted" />

                  <div className="d-flex">
                    <a
                      href="#"
                      className="btn btn-primary px-md-4 col col-md-auto me-2"
                    >
                      Buy now
                    </a>
                    <button className="btn btn-outline-primary col col-md-auto">
                      &nbsp;Add to cart
                    </button>
                  </div>
                </div>
              </div>
        </div>
      </div>

      
      <Footer/>
      
    </div>
  )
}
