import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// Component
import Navbar from "../component/customer/Navbar";
import Footer from "../component/customer/Footer";
// Utils
import {withAuth} from "../utils/gsspCustomer";

export const getServerSideProps = withAuth(context => {
    // Your normal `getServerSideProps` code here
    return { props: {} };
});

export default function Home({isLogin, currentUser}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isLogin={isLogin} currentUser={currentUser} />
      

      <div class="d-flex flex-row justify-content-center">
        <div >
          <img class="img-fluid" src="/temp/chip.png" alt="kategori" width="90" height="90" />
          <h6>Kategori</h6>
        </div>
        <div class="p-2">Flex item 2</div>
        <div class="p-2">Flex item 3</div>
      </div>
      
      <Footer/>
      
    </div>
  )
}
