import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// Component
import Navbar from "../component/customer/Navbar";
import Footer from "../component/customer/Footer";
// Utils
import {withAuth} from "../utils/gsspCustomer";

export const getServerSideProps = withAuth(context => {
    // Your normal `getServerSideProps` code here
    return { props: {} };
});

export default function Home({isLogin, currentUser}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isLogin={isLogin} currentUser={currentUser} />
      
      <h1>Ini Halaman Home</h1>
      
      <Footer/>
      
    </div>
  )
}
