import AccountMenu from "../component/customer/account-menu";
import AddressView from "../component/customer/address-view";
import styles from '../styles/Home.module.css';
import Head from 'next/head';

// Component
import Navbar from "../component/customer/Navbar";
import Footer from "../component/customer/Footer";
// Utils
import {withAuth} from "../utils/gsspCustomer";

export const getServerSideProps = withAuth(context => {
    // Your normal `getServerSideProps` code here
    return { props: {} };
});

export default function Home({isLogin, currentUser}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Informasi Akun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isLogin={isLogin} currentUser={currentUser} />
      
    <div className="container py-4">
    <div className="row g-3">
          <div className="col-lg-3">
            <AccountMenu current="profile" />
          </div>
          <div className="col-lg-9">
            <div className="row g-3">
              <div className="col-lg-9">
                <div className="card border-0 shadow-sm mb-3">
                  <div className="card-body">
                    <h4 className="card-title fw-semibold mt-2 mb-3">
                      Profil User
                    </h4>
                    <form className="row g-3">
                      <div className="col-md-6">
                        <label className="form-label">Nama</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="col-md-6">
                        <label className="form-label">Password</label>
                        <input
                          type="password"
                          className="form-control bg-light"
                          disabled
                        />
                        <button
                          type="button"
                          className="btn btn-sm btn-link float-end p-0 text-decoration-none">
                          Ubah Password
                        </button>
                      </div>
                      <div className="col-md-12 mt-0">
                        <label className="form-label">Nomor Telepon</label>
                        <div className="input-group">
                          <div>
                            <select className="form-select rounded-0 rounded-start bg-light">
                              <option>+95</option>
                            </select>
                          </div>
                          <input type="tel" className="form-control" />
                        </div>
                      </div>
                      <div className="col-md-12">
                        <label className="form-label">Email</label>
                        <input type="email" className="form-control" />
                      </div>

                      <div className="col-md-12 mt-4">
                        <button className="btn btn-primary float-start">
                          Update
                        </button>
                      </div>
                    </form>
                  </div>
                </div>

                <div className="card border-0 shadow-sm">
                  <div className="p-3 d-flex border-bottom">
                    <h5 className="my-auto fw-semibold">Alamat</h5>
                    <button className="btn btn-sm btn-primary ms-auto">
                      Tambah
                    </button>
                  </div>
                  <div className="card-body">
                    <div className="row row-cols-1 row-cols-lg-2 g-3">
                      <div className="col">
                        <AddressView />
                      </div>
                      <div className="col">
                        <AddressView />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-3"></div>
            </div>
          </div>
        </div>
      </div>
      <Footer/>
    </div>
  )
}