import CartItemRow from "../component/customer/cart-item-row";
import PricingCard from "../component/customer/pricing-card";
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// Component
import Navbar from "../component/customer/Navbar";
import Footer from "../component/customer/Footer";
// Utils
import {withAuth} from "../utils/gsspCustomer";

export const getServerSideProps = withAuth(context => {
    // Your normal `getServerSideProps` code here
    return { props: {} };
});

export default function Home({isLogin, currentUser}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Keranjang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isLogin={isLogin} currentUser={currentUser} />
      
    <div className="container py-4">
      <div className="row g-3">
        <div className="col-lg-8">
          <div className="card border-0 shadow-sm">
            <div className="card-header bg-white">
              <h5 className="my-2">Keranjang</h5>
            </div>
            <div className="card-body p-2">
              <div className="table-responsive">
                <table className="table table-borderless align-middle mb-0">
                  <tbody>
                    <CartItemRow />
                    <CartItemRow />
                    <CartItemRow />
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div className="col-lg-4">
          <PricingCard />
        </div>
      </div>
    </div>

      
      <Footer/>
      
    </div>
  )
}