import AccountMenu from "../component/customer/account-menu";
import OrderHistoryItem from "../component/customer/order-history-item";
import styles from '../styles/Home.module.css';
import Head from 'next/head';

// Component
import Navbar from "../component/customer/Navbar";
import Footer from "../component/customer/Footer";
// Utils
import {withAuth} from "../utils/gsspCustomer";

export const getServerSideProps = withAuth(context => {
    // Your normal `getServerSideProps` code here
    return { props: {} };
});

export default function Home({isLogin, currentUser}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Informasi Akun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isLogin={isLogin} currentUser={currentUser} />
      
    <div className="container py-4">
      <div className="row g-3">
          <div className="col-lg-3">
            <AccountMenu current="order-history" />
          </div>
          <div className="col-lg-9">
            <OrderHistoryItem id={20001} />
            <OrderHistoryItem id={20002} cancel />

            <nav className="float-end mt-3">
              <ul className="pagination">
                <li className="page-item">
                  <a className="page-link" href="#">
                    Prev
                  </a>
                </li>
                <li className="page-item">
                  <a className="page-link" href="#">
                    1
                  </a>
                </li>
                <li className="page-item">
                  <a className="page-link" href="#">
                    2
                  </a>
                </li>
                <li className="page-item">
                  <a className="page-link" href="#">
                    3
                  </a>
                </li>
                <li className="page-item">
                  <a className="page-link" href="#">
                    Next
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <Footer/>
    </div>
  )
}